openapi: 3.1.0
info:
  title: Runway MCP Server
  description: Generate images and videos using Runway ML. Server handles all task polling internally and returns completed results with media URLs.
  version: 1.1.0
servers:
  - url: https://runway-generator-liard.vercel.app

paths:
  /gpt-action:
    post:
      operationId: callRunwayMCP
      summary: Generate media with Runway ML
      description: |
        Execute Runway ML operations. The server handles all task polling internally and waits for completion before responding.
        
        **Key Features:**
        - Server-side polling: No need to manage tasks manually
        - Automatic completion: Returns final media URLs directly
        - Built-in timeout: 10-minute default timeout for generation tasks
        
        **Available Operations:**
        - `runway.text_to_image`: Generate images from text prompts
        - `runway.image_to_video`: Create videos from images with motion prompts
        - `runway.video_upscale`: Upscale videos to higher resolution
        - `runway.tasks.retrieve`: Get status of specific tasks
        - `runway.tasks.cancel`: Cancel running tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                  enum: ["2.0"]
                  description: JSON-RPC version
                id:
                  type: string
                  description: Unique request identifier
                method:
                  type: string
                  enum: ["tools/call"]
                  description: MCP method to call
                params:
                  type: object
                  properties:
                    name:
                      type: string
                      enum: 
                        - "runway.text_to_image"
                        - "runway.image_to_video"  
                        - "runway.video_upscale"
                        - "runway.tasks.retrieve"
                        - "runway.tasks.cancel"
                      description: Runway tool to execute
                    arguments:
                      type: object
                      description: |
                        Tool-specific arguments. Common parameters:
                        - `promptText`: Text description for generation (required for text_to_image)
                        - `promptImage`: URL to source image (required for image_to_video) 
                        - `model`: Runway model to use (defaults: gen4_image, gen4_turbo)
                        - `ratio`: Aspect ratio like "1024:1024", "1360:768", etc.
                        - `timeoutMs`: Custom timeout in milliseconds (default: 600000 = 10 minutes)
                      additionalProperties: true
                  required: ["name", "arguments"]
              required: ["jsonrpc", "id", "method", "params"]
            examples:
              text_to_image:
                summary: Generate an image from text
                value:
                  jsonrpc: "2.0"
                  id: "1"
                  method: "tools/call"
                  params:
                    name: "runway.text_to_image"
                    arguments:
                      promptText: "a beautiful sunset over mountains"
                      model: "gen4_image"
                      ratio: "1024:1024"
              image_to_video:
                summary: Generate a video from an image
                value:
                  jsonrpc: "2.0"
                  id: "2"
                  method: "tools/call"
                  params:
                    name: "runway.image_to_video"
                    arguments:
                      promptImage: "https://example.com/image.jpg"
                      promptText: "camera pans left, gentle movement"
                      model: "gen4_turbo"
              video_upscale:
                summary: Upscale a video to higher resolution
                value:
                  jsonrpc: "2.0"
                  id: "3"
                  method: "tools/call"
                  params:
                    name: "runway.video_upscale"
                    arguments:
                      video: "https://example.com/video.mp4"
                      model: "gen4_turbo"
      responses:
        "200":
          description: |
            Successful response with completed generation results. 
            Contains resource_link objects with direct URLs to generated media and task details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    enum: ["2.0"]
                  result:
                    type: object
                    properties:
                      content:
                        type: array
                        description: Array containing resource links and task information
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                              enum: ["resource_link", "text"]
                              description: Type of content item
                            resource:
                              type: string
                              description: Direct URL to generated media (for resource_link type)
                            name:
                              type: string 
                              description: Display name for the resource
                            text:
                              type: string
                              description: JSON string with task details (for text type)
                  id:
                    type: string
              example:
                jsonrpc: "2.0"
                result:
                  content:
                    - type: "resource_link"
                      resource: "https://media.runwayml.com/generated/image123.jpg"
                      name: "output_01"
                    - type: "text" 
                      text: '{"taskId": "task_abc123", "status": "SUCCEEDED", "output": ["https://media.runwayml.com/generated/image123.jpg"]}'
                id: "1"
        "400":
          description: Invalid request format
        "500":
          description: Server error